apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
    type: NodePort
  ports:
    - protocol: TCP
      nodePort: 30008
      port: 27017
      targetPort: 27017
